from appJar import gui
if __name__ == '__main__': 
	app = gui("Hello World","500x500")
	app.setSticky("news")
	app.setExpand("both")
	app.addImage("0x0", "","D:/Workspace/TryPy/grass_1.png",0,0)
	app.addImage("1x0", "","D:/Workspace/TryPy/grass_1.png",1,0)
	app.addImage("2x0", "","D:/Workspace/TryPy/grass_1.png",2,0)
	app.addImage("3x0", "","D:/Workspace/TryPy/grass_1.png",3,0)
	app.addImage("4x0", "","D:/Workspace/TryPy/grass_1.png",4,0)
	app.addImage("5x0", "","D:/Workspace/TryPy/grass_1.png",5,0)
	app.addImage("6x0", "","D:/Workspace/TryPy/grass_1.png",6,0)
	app.addImage("7x0", "","D:/Workspace/TryPy/grass_1.png",7,0)
	app.addImage("0x1", "","D:/Workspace/TryPy/grass_1.png",0,1)
	app.addImage("1x1", "","D:/Workspace/TryPy/grass_1.png",1,1)
	app.addImage("2x1", "","D:/Workspace/TryPy/grass_1.png",2,1)
	app.addImage("3x1", "","D:/Workspace/TryPy/grass_1.png",3,1)
	app.addImage("4x1", "","D:/Workspace/TryPy/grass_1.png",4,1)
	app.addImage("5x1", "","D:/Workspace/TryPy/grass_1.png",5,1)
	app.addImage("6x1", "","D:/Workspace/TryPy/grass_1.png",6,1)
	app.addImage("7x1", "","D:/Workspace/TryPy/grass_1.png",7,1)
	app.addImage("0x2", "","D:/Workspace/TryPy/grass_1.png",0,2)
	app.addImage("1x2", "","D:/Workspace/TryPy/grass_1.png",1,2)
	app.addImage("2x2", "","D:/Workspace/TryPy/grass_1.png",2,2)
	app.addImage("3x2", "","D:/Workspace/TryPy/grass_1.png",3,2)
	app.addImage("4x2", "","D:/Workspace/TryPy/grass_1.png",4,2)
	app.addImage("5x2", "","D:/Workspace/TryPy/grass_1.png",5,2)
	app.addImage("6x2", "","D:/Workspace/TryPy/grass_1.png",6,2)
	app.addImage("7x2", "","D:/Workspace/TryPy/grass_1.png",7,2)
	app.addImage("0x3", "","D:/Workspace/TryPy/grass_1.png",0,3)
	app.addImage("1x3", "","D:/Workspace/TryPy/grass_1.png",1,3)
	app.addImage("2x3", "","D:/Workspace/TryPy/grass_1.png",2,3)
	app.addImage("3x3", "","D:/Workspace/TryPy/grass_1.png",3,3)
	app.addImage("4x3", "","D:/Workspace/TryPy/grass_1.png",4,3)
	app.addImage("5x3", "","D:/Workspace/TryPy/grass_1.png",5,3)
	app.addImage("6x3", "","D:/Workspace/TryPy/grass_1.png",6,3)
	app.addImage("7x3", "","D:/Workspace/TryPy/grass_1.png",7,3)
	app.addImage("0x4", "","D:/Workspace/TryPy/grass_1.png",0,4)
	app.addImage("1x4", "","D:/Workspace/TryPy/grass_1.png",1,4)
	app.addImage("2x4", "","D:/Workspace/TryPy/grass_1.png",2,4)
	app.addImage("3x4", "","D:/Workspace/TryPy/grass_1.png",3,4)
	app.addImage("4x4", "","D:/Workspace/TryPy/grass_1.png",4,4)
	app.addImage("5x4", "","D:/Workspace/TryPy/grass_1.png",5,4)
	app.addImage("6x4", "","D:/Workspace/TryPy/grass_1.png",6,4)
	app.addImage("7x4", "","D:/Workspace/TryPy/grass_1.png",7,4)
	app.addImage("0x5", "","D:/Workspace/TryPy/grass_1.png",0,5)
	app.addImage("1x5", "","D:/Workspace/TryPy/grass_1.png",1,5)
	app.addImage("2x5", "","D:/Workspace/TryPy/grass_1.png",2,5)
	app.addImage("3x5", "","D:/Workspace/TryPy/grass_1.png",3,5)
	app.addImage("4x5", "","D:/Workspace/TryPy/grass_1.png",4,5)
	app.addImage("5x5", "","D:/Workspace/TryPy/grass_1.png",5,5)
	app.addImage("6x5", "","D:/Workspace/TryPy/grass_1.png",6,5)
	app.addImage("7x5", "","D:/Workspace/TryPy/grass_1.png",7,5)
	app.addImage("0x6", "","D:/Workspace/TryPy/grass_1.png",0,6)
	app.addImage("1x6", "","D:/Workspace/TryPy/grass_1.png",1,6)
	app.addImage("2x6", "","D:/Workspace/TryPy/grass_1.png",2,6)
	app.addImage("3x6", "","D:/Workspace/TryPy/grass_1.png",3,6)
	app.addImage("4x6", "","D:/Workspace/TryPy/grass_1.png",4,6)
	app.addImage("5x6", "","D:/Workspace/TryPy/grass_1.png",5,6)
	app.addImage("6x6", "","D:/Workspace/TryPy/grass_1.png",6,6)
	app.addImage("7x6", "","D:/Workspace/TryPy/grass_1.png",7,6)
	app.addImage("0x7", "","D:/Workspace/TryPy/grass_1.png",0,7)
	app.addImage("1x7", "","D:/Workspace/TryPy/grass_1.png",1,7)
	app.addImage("2x7", "","D:/Workspace/TryPy/grass_1.png",2,7)
	app.addImage("3x7", "","D:/Workspace/TryPy/grass_1.png",3,7)
	app.addImage("4x7", "","D:/Workspace/TryPy/grass_1.png",4,7)
	app.addImage("5x7", "","D:/Workspace/TryPy/grass_1.png",5,7)
	app.addImage("6x7", "","D:/Workspace/TryPy/grass_1.png",6,7)
	app.addImage("7x7", "","D:/Workspace/TryPy/grass_1.png",7,7)
	
	app.go()