from appJar import gui

if __name__ == '__main__':
    app = gui("Hello World", "500x500")
    app.setSticky("news")
    app.setExpand("both")
    app.addLabel("0x0", "", 0, 0)
    app.addLabel("1x0", "", 1, 0)
    app.addLabel("2x0", "", 2, 0)
    app.addLabel("3x0", "", 3, 0)
    app.addLabel("4x0", "", 4, 0)
    app.addLabel("5x0", "", 5, 0)
    app.addLabel("6x0", "", 6, 0)
    app.addLabel("7x0", "", 7, 0)
    app.addLabel("0x1", "", 0, 1)
    app.addLabel("1x1", "", 1, 1)
    app.addLabel("2x1", "", 2, 1)
    app.addLabel("3x1", "", 3, 1)
    app.addLabel("4x1", "", 4, 1)
    app.addLabel("5x1", "", 5, 1)
    app.addLabel("6x1", "", 6, 1)
    app.addLabel("7x1", "", 7, 1)
    app.addLabel("0x2", "", 0, 2)
    app.addLabel("1x2", "", 1, 2)
    app.addLabel("2x2", "", 2, 2)
    app.addLabel("3x2", "", 3, 2)
    app.addLabel("4x2", "", 4, 2)
    app.addLabel("5x2", "", 5, 2)
    app.addLabel("6x2", "", 6, 2)
    app.addLabel("7x2", "", 7, 2)
    app.addLabel("0x3", "", 0, 3)
    app.addLabel("1x3", "", 1, 3)
    app.addLabel("2x3", "", 2, 3)
    app.addLabel("3x3", "", 3, 3)
    app.addLabel("4x3", "", 4, 3)
    app.addLabel("5x3", "", 5, 3)
    app.addLabel("6x3", "", 6, 3)
    app.addLabel("7x3", "", 7, 3)
    app.addLabel("0x4", "", 0, 4)
    app.addLabel("1x4", "", 1, 4)
    app.addLabel("2x4", "", 2, 4)
    app.addLabel("3x4", "", 3, 4)
    app.addLabel("4x4", "", 4, 4)
    app.addLabel("5x4", "", 5, 4)
    app.addLabel("6x4", "", 6, 4)
    app.addLabel("7x4", "", 7, 4)
    app.addLabel("0x5", "", 0, 5)
    app.addLabel("1x5", "", 1, 5)
    app.addLabel("2x5", "", 2, 5)
    app.addLabel("3x5", "", 3, 5)
    app.addLabel("4x5", "", 4, 5)
    app.addLabel("5x5", "", 5, 5)
    app.addLabel("6x5", "", 6, 5)
    app.addLabel("7x5", "", 7, 5)
    app.addLabel("0x6", "", 0, 6)
    app.addLabel("1x6", "", 1, 6)
    app.addLabel("2x6", "", 2, 6)
    app.addLabel("3x6", "", 3, 6)
    app.addLabel("4x6", "", 4, 6)
    app.addLabel("5x6", "", 5, 6)
    app.addLabel("6x6", "", 6, 6)
    app.addLabel("7x6", "", 7, 6)
    app.addLabel("0x7", "", 0, 7)
    app.addLabel("1x7", "", 1, 7)
    app.addLabel("2x7", "", 2, 7)
    app.addLabel("3x7", "", 3, 7)
    app.addLabel("4x7", "", 4, 7)
    app.addLabel("5x7", "", 5, 7)
    app.addLabel("6x7", "", 6, 7)
    app.addLabel("7x7", "", 7, 7)

    app.setLabelBg("0x0", "white")
    app.setLabelBg("1x0", "black")
    app.setLabelBg("2x0", "white")
    app.setLabelBg("3x0", "black")
    app.setLabelBg("4x0", "white")
    app.setLabelBg("5x0", "black")
    app.setLabelBg("6x0", "white")
    app.setLabelBg("7x0", "black")
    app.setLabelBg("0x1", "black")
    app.setLabelBg("1x1", "white")
    app.setLabelBg("2x1", "black")
    app.setLabelBg("3x1", "white")
    app.setLabelBg("4x1", "black")
    app.setLabelBg("5x1", "white")
    app.setLabelBg("6x1", "black")
    app.setLabelBg("7x1", "white")
    app.setLabelBg("0x2", "white")
    app.setLabelBg("1x2", "black")
    app.setLabelBg("2x2", "white")
    app.setLabelBg("3x2", "black")
    app.setLabelBg("4x2", "white")
    app.setLabelBg("5x2", "black")
    app.setLabelBg("6x2", "white")
    app.setLabelBg("7x2", "black")
    app.setLabelBg("0x3", "black")
    app.setLabelBg("1x3", "white")
    app.setLabelBg("2x3", "black")
    app.setLabelBg("3x3", "white")
    app.setLabelBg("4x3", "black")
    app.setLabelBg("5x3", "white")
    app.setLabelBg("6x3", "black")
    app.setLabelBg("7x3", "white")
    app.setLabelBg("0x4", "white")
    app.setLabelBg("1x4", "black")
    app.setLabelBg("2x4", "white")
    app.setLabelBg("3x4", "black")
    app.setLabelBg("4x4", "white")
    app.setLabelBg("5x4", "black")
    app.setLabelBg("6x4", "white")
    app.setLabelBg("7x4", "black")
    app.setLabelBg("0x5", "black")
    app.setLabelBg("1x5", "white")
    app.setLabelBg("2x5", "black")
    app.setLabelBg("3x5", "white")
    app.setLabelBg("4x5", "black")
    app.setLabelBg("5x5", "white")
    app.setLabelBg("6x5", "black")
    app.setLabelBg("7x5", "white")
    app.setLabelBg("0x6", "white")
    app.setLabelBg("1x6", "black")
    app.setLabelBg("2x6", "white")
    app.setLabelBg("3x6", "black")
    app.setLabelBg("4x6", "white")
    app.setLabelBg("5x6", "black")
    app.setLabelBg("6x6", "white")
    app.setLabelBg("7x6", "black")
    app.setLabelBg("0x7", "black")
    app.setLabelBg("1x7", "white")
    app.setLabelBg("2x7", "black")
    app.setLabelBg("3x7", "white")
    app.setLabelBg("4x7", "black")
    app.setLabelBg("5x7", "white")
    app.setLabelBg("6x7", "black")
    app.setLabelBg("7x7", "white")

    app.addImage
    app.go()
